rm(list=ls())
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
install.packages(c("tidyverse","neuralnet","conflicted", "GGally"))
library(tidyverse)
library(neuralnet)
library(conflicted)
library(GGally)
conflicts_prefer(dplyr::select)

beer<-read.csv("https://www.dropbox.com/s/nc3dygybis4wkbk/beer_reviews.csv?dl=1", header=TRUE)
head(beer)
View(head(beer))
beer2<-as_tibble(beer)
View(beer2)
beer_map<-select(beer2, brewery_id,brewery_name, beer_name, beer_beerid)
beer2<-select(beer2,-review_profilename, -brewery_name, -beer_name, -review_time)
View(beer2)
ggpairs(beer2,cardinality_threshold=104)
abv.dot<-ggplot(beer2, aes(beer_abv))
abv.scat<-ggplot(beer2, aes(beer_beerid, beer_abv))
abv.scat+geom_point()
abv.dot+geom_dotplot()
pc.beer2<-prcomp(beer2,scale=TRUE)


